name: Test
on:
  push:
    branches:
      - main
  pull_request:

env:
  SLACK_CHANNEL: "#reviewdog-slack-test"
  SLACK_USERNAME: "Lint Test Bot"
  SLACK_ICON_EMOJI: ":test:"

jobs:
  test-check:
    name: Lint Check (github-check)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          filter_mode: nofilter
          level: warning
          fail_level: warning
          workdir: ./testdata/

          # AI 리뷰어 설정
          ai_reviewer_use_mock_api: true
          ai_reviewer_enabled: true
          ai_reviewer_api_key: ${{ secrets.OPENAI_API_KEY }}
          ai_reviewer_language: ko
          ai_reviewer_model: gpt-4o
          ai_reviewer_file_patterns: "**/*.{js,jsx,ts,tsx}"

          # Axe 리뷰어 설정
          axe_reviewer_enabled: true
          axe_reviewer_file_patterns: "**/*.{html,jsx,tsx}"

          # HTML 검증기 설정
          html_reviewer_enabled: true
          html_reviewer_file_patterns: "**/*.{html,htm}"
          html_reviewer_use_mock_api: true

          # CSS 검증기 설정
          css_reviewer_enabled: true
          css_reviewer_file_patterns: "**/*.{css,scss,less}"
          css_reviewer_use_mock_api: true

          # 인라인 코드 검출기 설정
          inline_code_reviewer_enabled: true
          inline_code_reviewer_file_patterns: "**/*.{html,htm}"

          # 이미지 최적화 검사기 설정
          image_reviewer_enabled: true
          image_reviewer_file_patterns: "**/*.{html,htm,jpg,jpeg,png,gif,webp,svg}"

          # 페이지 구조 분석기 설정
          page_structure_reviewer_enabled: true
          page_structure_reviewer_file_patterns: "**/*.{html,htm}"

          debug: true

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: Lint Check (github-pr-check)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          filter_mode: nofilter
          level: warning
          fail_level: warning
          workdir: ./testdata/

          # AI 리뷰어 설정
          ai_reviewer_use_mock_api: true
          ai_reviewer_enabled: true
          ai_reviewer_api_key: ${{ secrets.OPENAI_API_KEY }}
          ai_reviewer_language: ko
          ai_reviewer_model: gpt-4o
          ai_reviewer_file_patterns: "**/*.{js,jsx,ts,tsx}"

          # Axe 리뷰어 설정
          axe_reviewer_enabled: true
          axe_reviewer_file_patterns: "**/*.{html,jsx,tsx}"

          # HTML 검증기 설정
          html_reviewer_enabled: true
          html_reviewer_file_patterns: "**/*.{html,htm}"
          html_reviewer_use_mock_api: true

          # CSS 검증기 설정
          css_reviewer_enabled: true
          css_reviewer_file_patterns: "**/*.{css,scss,less}"
          css_reviewer_use_mock_api: true

          # 인라인 코드 검출기 설정
          inline_code_reviewer_enabled: true
          inline_code_reviewer_file_patterns: "**/*.{html,htm}"

          # 이미지 최적화 검사기 설정
          image_reviewer_enabled: true
          image_reviewer_file_patterns: "**/*.{html,htm,jpg,jpeg,png,gif,webp,svg}"

          # 페이지 구조 분석기 설정
          page_structure_reviewer_enabled: true
          page_structure_reviewer_file_patterns: "**/*.{html,htm}"

          debug: true

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: Lint Check (github-pr-review)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
          level: error
          fail_level: error
          workdir: ./testdata/

          # AI 리뷰어 설정
          ai_reviewer_use_mock_api: true
          ai_reviewer_enabled: true
          ai_reviewer_api_key: ${{ secrets.OPENAI_API_KEY }}
          ai_reviewer_language: ko
          ai_reviewer_model: gpt-4o
          ai_reviewer_file_patterns: "**/*.{js,jsx,ts,tsx}"

          # Axe 리뷰어 설정
          axe_reviewer_enabled: true
          axe_reviewer_file_patterns: "**/*.{html,jsx,tsx}"

          # HTML 검증기 설정
          html_reviewer_enabled: true
          html_reviewer_file_patterns: "**/*.{html,htm}"
          html_reviewer_use_mock_api: true

          # CSS 검증기 설정
          css_reviewer_enabled: true
          css_reviewer_file_patterns: "**/*.{css,scss,less}"
          css_reviewer_use_mock_api: true

          # 인라인 코드 검출기 설정
          inline_code_reviewer_enabled: true
          inline_code_reviewer_file_patterns: "**/*.{html,htm}"

          # 이미지 최적화 검사기 설정
          image_reviewer_enabled: true
          image_reviewer_file_patterns: "**/*.{html,htm,jpg,jpeg,png,gif,webp,svg}"

          # 페이지 구조 분석기 설정
          page_structure_reviewer_enabled: true
          page_structure_reviewer_file_patterns: "**/*.{html,htm}"

          debug: true
